In [31]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

In [32]:
dataset_url="https://raw.githubusercontent.com/apogiatzis/breast-cancer-azure-ml-notebook/refs/heads/master/breast-cancer-data.csv"
dataset=pd.read_csv(dataset_url)

In [33]:
dataset.head(5)

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [34]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [35]:
# distribution of y-variable
dataset.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [36]:
dataset.diagnosis.value_counts()/len(dataset) *100

diagnosis
B    62.741652
M    37.258348
Name: count, dtype: float64

In [37]:
dataset.shape

(569, 33)

In [38]:
dataset['diagnosis']=dataset['diagnosis'].map({'M':1, 'B':0})

In [39]:
dataset.head()

         id  diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302          1  ...                  0.11890          NaN
1    842517          1  ...                  0.08902          NaN
2  84300903          1  ...                  0.08758          NaN
3  84348301          1  ...                  0.17300          NaN
4  84358402          1  ...                  0.07678          NaN

[5 rows x 33 columns]

In [40]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    int64
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(2)
memory usage: 146.8 KB

In [41]:
X=dataset.drop(['diagnosis','id'],axis=1)
y=dataset['diagnosis']

In [42]:
X

     radius_mean  texture_mean  ...  fractal_dimension_worst  Unnamed: 32
0          17.99         10.38  ...                  0.11890          NaN
1          20.57         17.77  ...                  0.08902          NaN
2          19.69         21.25  ...                  0.08758          NaN
3          11.42         20.38  ...                  0.17300          NaN
4          20.29         14.34  ...                  0.07678          NaN
..           ...           ...  ...                      ...          ...
564        21.56         22.39  ...                  0.07115          NaN
565        20.13         28.25  ...                  0.06637          NaN
566        16.60         28.08  ...                  0.07820          NaN
567        20.60         29.33  ...                  0.12400          NaN
568         7.76         24.54  ...                  0.07039          NaN

[569 rows x 31 columns]

In [43]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [44]:
# train test split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [45]:
len(X_train)

455

In [46]:
len(X_test)

114

In [48]:
# feture scaling


# standardization,Normalization

In [49]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.13/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [50]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  2.09724217,
         1.88645014,         nan],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  1.89116053,
         2.49783848,         nan],
       [-1.39998202, -1.24962228, -1.34520926, ...,  0.59760192,
         0.0578942 ,         nan],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -0.70863864,
        -1.27145475,         nan],
       [-0.03896885,  0.10207345, -0.03137406, ...,  0.43432185,
         1.21336207,         nan],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.3345212 ,
        -0.84628745,         nan]])

In [51]:
X_test

array([[-0.46649743, -0.13728933, -0.44421138, ...,  0.17275669,
         0.20372995,         nan],
       [ 1.36536344,  0.49866473,  1.30551088, ..., -0.561211  ,
        -1.00838949,         nan],
       [ 0.38006578,  0.06921974,  0.40410139, ..., -0.10783139,
        -0.20629287,         nan],
       ...,
       [-0.73547237, -0.99852603, -0.74138839, ..., -0.3820785 ,
        -0.32408328,         nan],
       [ 0.02898271,  2.0334026 ,  0.0274851 , ..., -1.60905688,
        -0.33137507,         nan],
       [ 1.87216885,  2.80077153,  1.80354992, ..., -0.05868885,
        -0.09467243,         nan]])

In [52]:
# model building

In [54]:
# rf

from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier()
model.fit(X_train,Y_train)

RandomForestClassifier()

In [55]:
# predicting the test values

y_pred=model.predict(X_test)

In [57]:
# metrics

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

result=accuracy_score(Y_test,y_pred)
print("accuracy of the base rf model is : ",round(result*100,2))

accuracy of the base rf model is :  96.49

In [62]:
cm=confusion_matrix(Y_test,y_pred)
print("cm is : ")
print(cm)

cm is :
[[70  1]
 [ 3 40]]

In [61]:
cr=classification_report(Y_test,y_pred)
print("classification report is : ")
print(cr)

classification report is :
              precision    recall  f1-score   support

           0       0.96      0.99      0.97        71
           1       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

In [63]:
# Manual HPO

n_estimators_list=[1,2,3,10,50,100,200]
for estim_list in n_estimators_list:
  model=RandomForestClassifier(n_estimators=estim_list)
  model.fit(X_train,Y_train)
  y_pred=model.predict(X_test)
  result=accuracy_score(Y_test,y_pred)
  print("\n Estimator Value",estim_list)
  print("accuracy score", result)

 Estimator Value 1
accuracy score 0.9824561403508771

 Estimator Value 2
accuracy score 0.9298245614035088

 Estimator Value 3
accuracy score 0.956140350877193

 Estimator Value 10
accuracy score 0.9473684210526315

 Estimator Value 50
accuracy score 0.956140350877193

 Estimator Value 100
accuracy score 0.9649122807017544

 Estimator Value 200
accuracy score 0.9649122807017544

In [64]:
leaf_size=[1,2,3,4,5,10]
for i in leaf_size:
    model=RandomForestClassifier(n_estimators=1,min_samples_leaf=i)
    model.fit(X_train,Y_train)
    y_pred=model.predict(X_test)
    result=accuracy_score(Y_test,y_pred)
    print("\n Estimator Value",i)
    print("accuracy score", result)

 Estimator Value 1
accuracy score 0.9473684210526315

 Estimator Value 2
accuracy score 0.956140350877193

 Estimator Value 3
accuracy score 0.9385964912280702

 Estimator Value 4
accuracy score 0.956140350877193

 Estimator Value 5
accuracy score 0.956140350877193

 Estimator Value 10
accuracy score 0.9122807017543859

In [65]:
# so min_samples_leaf=1 and n_estimators=1 giving me best result

In [66]:
# Random Search cv
n_estimators=[int(x) for x in np.linspace(start=100 , stop=1000 ,num=10)]

In [68]:
# numbers from 100 to 1000
n_estimators

[100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

In [70]:
from sklearn.model_selection import RandomizedSearchCV
max_depth=[int(x) for x in np.linspace(start=10, stop=110,num=11)]
min_samples_leaf=[1,2,4,10,20,50,100]
min_samples_split=[2,3,4,5,8,10,20,50,100,110]
bootstrap=[True,False]

# create random grid

random_grid={'n_estimators': n_estimators,
             'max_depth': max_depth,
             'min_samples_split': min_samples_split,
             'bootstrap': bootstrap,
             'min_samples_leaf': min_samples_leaf}

In [71]:
# on each iteration the algo will choose diffrent combination of the fetures,
# altogether there are 15400 combinations.however the benifit of random search is that we are not trying
# everycombination but selecting random sample values still get the wide range of values.

In [74]:
rf=RandomForestClassifier()
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,n_jobs=-1)

rf_random.fit(X_train,Y_train)

RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110],
                                        'min_samples_leaf': [1, 2, 4, 10, 20,
                                                             50, 100],
                                        'min_samples_split': [2, 3, 4, 5, 8, 10,
                                                              20, 50, 100,
                                                              110],
                                        'n_estimators': [100, 200, 300, 400,
                                                         500, 600, 700, 800,
                                                         900, 1000]})

In [78]:
def evaluate(model,test_fetures,test_labels):
  predictions=model.predict(test_fetures)
  accuracy=accuracy_score(test_labels,predictions)
  print("model performance")
  print("accuracy = {:0.2f}%",format(accuracy))
  return accuracy

In [79]:
base_model=RandomForestClassifier(n_estimators=5,random_state=42)
base_model.fit(X_train,Y_train)
base_accuracy=evaluate(base_model,X_test,Y_test)

model performance
accuracy = {:0.2f}% 0.956140350877193

In [80]:
best_random=rf_random.best_estimator_
print(best_random)

RandomForestClassifier(bootstrap=False, max_depth=10, min_samples_leaf=2,
                       n_estimators=700)